// Footer — a slim signature strip: wordmark, a carrier signal with a travelling
// pulse, and the "generated in code" sign-off.

import { Doc, el, f } from '../lib/svg.mjs';
import { frame, linear, brand } from '../theme.mjs';

const W = 860;
const H = 88;

export function footer(ts, t, { config, data }) {
  const doc = new Doc(ts, { width: W, height: H, title: `${config.wordmark} — end of transmission`, desc: 'Every panel on this profile is generated by scripts/build.mjs and refreshed daily.' });
  const dark = t.name === 'dark';
  const { back, front } = frame(doc, t, {
    r: 18,
    glows: [{ cx: 430, cy: 120, rx: 320, ry: 90, color: t.aurora.violet, o: dark ? 0.3 : 0.55, drift: [40, 0], dur: 18 }],
    fade: [0.5, 0.5, 0.6],
  });
  const out = [back];

  const word = doc.ts.path(config.wordmark, { x: 26, y: 42, size: 14, stack: 'display', tracking: 0.28 });
  const cap = doc.ts.capHeight('display', 14);
  out.push(el('path', { d: word.d, fill: `url(#${linear(doc, t.chrome, { x1: 0, y1: f(42 - cap), x2: 0, y2: 42, units: 'userSpaceOnUse' })})` }));
  out.push(doc.text(`© ${data.syncedAt.slice(0, 4)}  ·  ${config.handle}  ·  ${config.location.city}`, { x: 26, y: 62, size: 9.5, stack: 'mono', fill: t.ink3, tracking: 0.1 }));

  // Carrier line with a heartbeat blip; a pulse of light runs along it.
  const x0 = 250;
  const x1 = 600;
  const mid = (x0 + x1) / 2;
  const y = 44;
  const d = `M${x0} ${y}H${mid - 26}l6 -9 7 20 6 -26 6 22 5 -7H${x1}`;
  out.push(el('path', { d, fill: 'none', stroke: t.line3, 'stroke-width': 1.2, 'stroke-linejoin': 'round' }));
  doc.css('.sig{stroke-dasharray:.12 .88;animation:sig 4.5s cubic-bezier(.45,0,.55,1) infinite}@keyframes sig{from{stroke-dashoffset:1.12}to{stroke-dashoffset:0}}');
  out.push(el('path', { d, pathLength: 1, fill: 'none', stroke: `url(#${brand(doc, t)})`, 'stroke-width': 1.8, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', class: 'sig' }));
  for (const x of [x0, x1]) out.push(el('circle', { cx: x, cy: y, r: 2.2, fill: t.ink3 }));

  out.push(doc.text('END OF TRANSMISSION', { x: W - 26, y: 42, size: 10, stack: 'monoMd', fill: t.ink2, tracking: 0.22, anchor: 'end' }));
  out.push(doc.text('Every pixel generated in code — scripts/build.mjs', { x: W - 26, y: 62, size: 11, stack: 'sans', fill: t.ink3, anchor: 'end' }));
  out.push(front);
  return doc.render(out.join('\n'));
}
