// README.md is generated: a column of <picture> panels that follow the viewer's
// GitHub theme, project cards linked two per row, and a text twin of the
// telemetry (the chart's table view) for screen readers and search.

import { esc } from './lib/svg.mjs';
import { fmt } from './theme.mjs';
import { languageMix } from './render/telemetry.mjs';

export const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

export function readme(config, data) {
  const base = `https://raw.githubusercontent.com/${config.login}/${config.login}/main/assets/`;
  const picture = (name, alt, width = '100%') =>
    `<picture><source media="(prefers-color-scheme: dark)" srcset="${base}${name}-dark.svg">` +
    `<source media="(prefers-color-scheme: light)" srcset="${base}${name}-light.svg">` +
    `<img alt="${esc(alt)}" src="${base}${name}-dark.svg" width="${width}"></picture>`;
  const block = (...lines) => ['<p align="center">', ...lines, '</p>'].join('\n');

  const cards = config.projects.map(
    (p) => `<a href="https://github.com/${config.login}/${p.repo}">${picture(`project-${slug(p.repo)}`, `${p.title} — ${p.desc}`, '49%')}</a>`,
  );
  const rows = [];
  for (let i = 0; i < cards.length; i += 2) rows.push(block(...cards.slice(i, i + 2)));

  const mix = languageMix(config, data);
  const pct = (s) => `${(s * 100).toFixed(1)}%`;
  const delta = data.last30 - data.prev30;
  const table = [
    '| Metric | Value |',
    '| :-- | --: |',
    `| Contributions · past 12 months | ${fmt(data.contributions.total)} |`,
    `| Commits · past 12 months | ${fmt(data.contributions.commits)} |`,
    data.peak.date ? `| Peak day · ${data.peak.date} | ${fmt(data.peak.count)} |` : '',
    `| Last 30 days | ${fmt(data.last30)} (${delta >= 0 ? '+' : '−'}${fmt(Math.abs(delta))} vs prior 30) |`,
    ...mix.listed.map((l) => `| ${l.name} | ${pct(l.share)} |`),
    `| Other (${mix.other.count} languages) | ${pct(mix.other.share)} |`,
  ].filter(Boolean);

  return [
    `<!-- Generated by scripts/build.mjs from profile.config.mjs — edit those, then \`npm run build\`. -->`,
    '',
    block(picture('hero', `${config.wordmark} · ${config.role.titleEn} — ${config.tagline} · ${config.taglineEn}`)),
    '',
    block(picture('identity', `${config.role.title} · ${config.role.titleEn} — ${config.role.org} · ${config.location.cityCn}`)),
    '',
    block(picture('stack', `Core stack — ${config.stack.map((l) => `${l.layer}: ${l.items.map((i) => i[1]).join(', ')}`).join(' / ')}`)),
    '',
    block(picture('work', 'Selected work')),
    '',
    rows.join('\n\n'),
    '',
    block(picture('telemetry', `Telemetry — ${fmt(data.contributions.total)} contributions in the past 12 months, ${fmt(data.last30)} in the last 30 days`)),
    '',
    '<div align="center">',
    '<details>',
    '<summary><sub>Telemetry as text · 文本版数据</sub></summary>',
    '',
    ...table,
    '',
    `<sub>Synced ${data.syncedAt} UTC · public activity only</sub>`,
    '</details>',
    '</div>',
    '',
    block(picture('footer', 'End of transmission — generated in code')),
    '',
  ].join('\n');
}
